// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ActualizarUsuarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void actualizarUsuario() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(883, 995));
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(1) .oxd-text")).click();
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(1) .card-center > .card-item > .oxd-table-cell:nth-child(1) .header")).click();
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(1) .oxd-icon-button:nth-child(2) > .oxd-icon")).click();
    driver.findElement(By.cssSelector(".oxd-autocomplete-text-input > input")).click();
    driver.findElement(By.cssSelector(".oxd-autocomplete-text-input > input")).sendKeys("Chasity Harper Bernhard");
    driver.findElement(By.cssSelector(".bi-caret-up-fill")).click();
    driver.findElement(By.cssSelector(".oxd-autocomplete-text-input > input")).click();
    driver.findElement(By.cssSelector(".oxd-autocomplete-text-input > input")).sendKeys("Chasity Harper Bernhard-Mills");
    {
      WebElement element = driver.findElement(By.cssSelector(".oxd-grid-item:nth-child(4) .oxd-input-group__label-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(1) .oxd-icon-button:nth-child(2) > .oxd-icon")).click();
    driver.findElement(By.cssSelector(".oxd-button--ghost")).click();
  }
}
