// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EliminarusuarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.firefox());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void eliminarusuario() {
    // Test name: Eliminar usuario
    // Step # | name | target | value
    // 1 | open | /web/index.php/dashboard/index | 
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index");
    // 2 | setWindowSize | 1145x653 | 
    driver.manage().window().setSize(new Dimension(1145, 653));
    // 3 | mouseOver | linkText=Upgrade | 
    {
      WebElement element = driver.findElement(By.linkText("Upgrade"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | mouseOut | linkText=Upgrade | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 5 | mouseOver | css=.oxd-main-menu-item-wrapper:nth-child(1) .oxd-text | 
    {
      WebElement element = driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(1) .oxd-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | css=.oxd-main-menu-item-wrapper:nth-child(1) .oxd-text | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | mouseOver | css=.oxd-main-menu-item-wrapper:nth-child(1) .oxd-icon | 
    {
      WebElement element = driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(1) .oxd-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | mouseOut | css=.oxd-main-menu-item-wrapper:nth-child(1) .oxd-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 9 | click | css=.oxd-main-menu-item-wrapper:nth-child(1) .oxd-text | 
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(1) .oxd-text")).click();
    // 10 | mouseOver | css=.active > .oxd-text | 
    {
      WebElement element = driver.findElement(By.cssSelector(".active > .oxd-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 11 | mouseOut | css=.active > .oxd-text | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 12 | click | css=.oxd-table-card:nth-child(2) .oxd-table-card-cell-checkbox .oxd-icon | 
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(2) .oxd-table-card-cell-checkbox .oxd-icon")).click();
    // 13 | click | css=.oxd-table-card:nth-child(2) .oxd-table-card-cell-checkbox .oxd-icon | 
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(2) .oxd-table-card-cell-checkbox .oxd-icon")).click();
    // 14 | click | css=.oxd-table-card:nth-child(3) .oxd-table-card-cell-checkbox .oxd-icon | 
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(3) .oxd-table-card-cell-checkbox .oxd-icon")).click();
    // 15 | click | css=.oxd-table-card:nth-child(3) .oxd-icon-button:nth-child(1) > .oxd-icon | 
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(3) .oxd-icon-button:nth-child(1) > .oxd-icon")).click();
    // 16 | click | css=.orangehrm-button-margin:nth-child(2) | 
    driver.findElement(By.cssSelector(".orangehrm-button-margin:nth-child(2)")).click();
    // 17 | click | css=.oxd-table-card:nth-child(3) .oxd-table-cell:nth-child(3) > div | 
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(3) .oxd-table-cell:nth-child(3) > div")).click();
  }
}
