// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UsernameyPasswordvaciosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.firefox());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void usernameyPasswordvacios() {
    // Test name: Username y Password vacios
    // Step # | name | target | value
    // 1 | open | /web/index.php/auth/login | 
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    // 2 | setWindowSize | 1366x720 | 
    driver.manage().window().setSize(new Dimension(1366, 720));
    // 3 | click | name=username | 
    driver.findElement(By.name("username")).click();
    // 4 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 5 | click | css=.oxd-button | 
    driver.findElement(By.cssSelector(".oxd-button")).click();
    // 6 | close |  | 
    driver.close();
  }
}
